/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Camera: typeof import('./src/components/Camera.vue')['default']
    ErrorMessage: typeof import('./src/components/ErrorMessage.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ListView: typeof import('./src/components/ListView.vue')['default']
    PrimaryButton: typeof import('./src/components/PrimaryButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectionList: typeof import('./src/components/SelectionList.vue')['default']
    Tab: typeof import('./src/components/Tab.vue')['default']
    ThemeButton: typeof import('./src/components/ThemeButton.vue')['default']
  }
}
